swagger: "2.0"
info:
  title: Skin Care Sale System API
  description: API for Skin Care Sale System
  version: 1.0.0
host: localhost:8080
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'

tags:
  - name: Authentication
    description: Operations related to user authentication
  - name: Products
    description: Operations related to products
  - name: Users
    description: Operations related to users

paths:
  /auth/register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      description: Register a new user
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: User object
          schema:
            type: object
            properties:
              email:
                type: string
                format: email
              password:
                type: string
                format: password
              confirmPassword:
                type: string
                format: password
      responses:
        201:
          description: User created
          schema:
            type: object
            properties:
              message:
                type: string
              data:
                type: object
                properties:
                  _id:
                    type: string
                  email:
                    type: string
                  password:
                    type: string
                  __v:
                    type: integer
        400:
          description: Bad request
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: array
                items:
                  type: object
                  properties:
                    param:
                      type: string
                    msg:
                      type: string

  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login to the system
      description: Login to the system
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: User object
          schema:
            type: object
            properties:
              email:
                type: string
                format: email
              password:
                type: string
                format: password
      responses:
        200:
          description: Login successful
          schema:
            type: object
            properties:
              message:
                type: string
              data:
                type: object
                properties:
                  _id:
                    type: string
                  email:
                    type: string
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
        400:
          description: Bad request
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: array
                items:
                  type: object
                  properties:
                    param:
                      type: string
                    msg:
                      type: string

  /auth/verify-email/{tokenVerify}/{id}:
    get:
      tags:
        - Authentication
      summary: Verify email
      description: Verify email
      parameters:
        - in: path
          name: tokenVerify
          description: Verification token
          required: true
          type: string
        - in: path
          name: id
          description: User ID
          required: true
          type: string
      responses:
        200:
          description: Email verified
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Bad request
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: array
                items:
                  type: object
                  properties:
                    param:
                      type: string
                    msg:
                      type: string

  /auth/reset-password:
    post:
      tags:
        - Authentication
      summary: Send reset password email
      description: Send reset password email
      consumes:
        - application/json
      parameters:
        - in: body
          name: email
          description: User email
          schema:
            type: object
            properties:
              email:
                type: string
                format: email
      responses:
        200:
          description: Reset password email sent
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Bad request
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: array
                items:
                  type: object
                  properties:
                    param:
                      type: string
                    msg:
                      type: string

  /auth/verify-reset-password/{token}/{userId}:
    post:
      tags:
        - Authentication
      summary: Verify reset password
      description: Verify reset password
      consumes:
        - application/json
      parameters:
        - in: path
          name: token
          description: Reset token
          required: true
          type: string
        - in: path
          name: userId
          description: User ID
          required: true
          type: string
        - in: body
          name: passwords
          description: New passwords
          schema:
            type: object
            properties:
              newPassword:
                type: string
                format: password
              confirmNewPassword:
                type: string
                format: password
      responses:
        200:
          description: Password updated successfully
          schema:
            type: object
            properties:
              message:
                type: string
        400:
          description: Bad request
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: array
                items:
                  type: object
                  properties:
                    param:
                      type: string
                    msg:
                      type: string

  /products:
    get:
      tags:
        - Products
      summary: Get all products
      description: Retrieve a list of all products
      responses:
        200:
          description: Successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Product"
        500:
          description: Internal server error

    post:
      tags:
        - Products
      summary: Create a new product
      description: Add a new product to the database
      parameters:
        - in: body
          name: product
          description: Product object to be created
          required: true
          schema:
            $ref: "#/definitions/Product"
      responses:
        201:
          description: Product created successfully
        400:
          description: Invalid input
        500:
          description: Internal server error

  /products/{id}:
    get:
      tags:
        - Products
      summary: Get product by ID
      description: Retrieve a product by its ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
          description: Product ID
      responses:
        200:
          description: Successful operation
          schema:
            $ref: "#/definitions/Product"
        404:
          description: Product not found
        500:
          description: Internal server error

    put:
      tags:
        - Products
      summary: Update product by ID
      description: Update the details of an existing product
      parameters:
        - in: path
          name: id
          required: true
          type: string
          description: Product ID
        - in: body
          name: product
          description: Updated product object
          required: true
          schema:
            $ref: "#/definitions/Product"
      responses:
        200:
          description: Product updated successfully
        400:
          description: Invalid input
        404:
          description: Product not found
        500:
          description: Internal server error

    delete:
      tags:
        - Products
      summary: Delete product by ID
      description: Remove a product from the database
      parameters:
        - in: path
          name: id
          required: true
          type: string
          description: Product ID
      responses:
        200:
          description: Product deleted successfully
        404:
          description: Product not found
        500:
          description: Internal server error

  /users:
    get:
      tags:
        - Users
      summary: Get all users
      description: Retrieve a list of all users from the system.
      operationId: getAllUsers
      produces:
        - application/json
      security:
        - Bearer: []
      responses:
        200:
          description: Users retrieved successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Get all users successfully"
              data:
                type: array
                items:
                  $ref: "#/definitions/User"
        404:
          description: No users found
          schema:
            type: object
            properties:
              message:
                type: string
                example: "No users found"
        500:
          description: Internal server error
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Internal server error"

  /users/{id}:
    get:
      tags:
        - Users
      summary: Get user by ID
      description: Retrieve a user by their ID
      parameters:
        - in: path
          name: id
          required: true
          type: string
          description: User ID
      responses:
        200:
          description: Get user by ID successfully
          schema:
            type: object
            properties:
              message:
                type: string
              data:
                $ref: "#/definitions/User"
        404:
          description: User not found
          schema:
            type: object
            properties:
              message:
                type: string
        500:
          description: Internal server error
          schema:
            type: object
            properties:
              message:
                type: string

    put:
      tags:
        - Users
      summary: Update user by ID
      description: Update the details of an existing user
      parameters:
        - in: path
          name: id
          required: true
          type: string
          description: User ID
        - in: body
          name: user
          description: Updated user object
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: Update user by ID successfully
          schema:
            type: object
            properties:
              message:
                type: string
              data:
                $ref: "#/definitions/User"
        404:
          description: User not found
          schema:
            type: object
            properties:
              message:
                type: string
        500:
          description: Internal server error
          schema:
            type: object
            properties:
              message:
                type: string

definitions:
  Product:
    type: object
    properties:
      name:
        type: string
        example: "Facial Cleanser"
      ingredient:
        type: string
        example: "Aloe Vera, Vitamin E"
      category:
        type: string
        example: "Skincare"
      stock:
        type: integer
        example: 100
      image:
        type: string
        example: "https://example.com/product.jpg"
      rating:
        type: number
        format: float
        example: 4.5
      purchaseCount:
        type: integer
        example: 50
      description:
        type: string
        example: "A gentle cleanser for all skin types."
      isDisabled:
        type: boolean
        example: false

  User:
    type: object
    properties:
      _id:
        type: string
      email:
        type: string
      password:
        type: string
      __v:
        type: integer
